[package]
name = "asciiren"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "6.0.0"
image = "0.24"
termion = "1.5"
clap = { version = "4.1", features = ["derive"] }
crossterm = "0.25"
rayon = "1.5"